export const ROLE_PERMISSIONS = {
  customer: {
    canViewOrders: true,
    canCreateOrders: true,
    canUpdateOrderStatus: false,
    canViewMenu: true,
    canManageMenu: false,
    canViewTables: false,
    canManageTables: false,
    canViewAnalytics: false,
    canManageUsers: false,
  },
  waiter: {
    canViewOrders: true,
    canCreateOrders: true,
    canUpdateOrderStatus: true,
    canViewMenu: true,
    canManageMenu: false,
    canViewTables: true,
    canManageTables: false,
    canViewAnalytics: false,
    canManageUsers: false,
  },
  chef: {
    canViewOrders: true,
    canCreateOrders: false,
    canUpdateOrderStatus: true,
    canViewMenu: true,
    canManageMenu: false,
    canViewTables: false,
    canManageTables: false,
    canViewAnalytics: false,
    canManageUsers: false,
  },
  manager: {
    canViewOrders: true,
    canCreateOrders: true,
    canUpdateOrderStatus: true,
    canViewMenu: true,
    canManageMenu: true,
    canViewTables: true,
    canManageTables: true,
    canViewAnalytics: true,
    canManageUsers: true,
  },
  admin: {
    canViewOrders: true,
    canCreateOrders: true,
    canUpdateOrderStatus: true,
    canViewMenu: true,
    canManageMenu: true,
    canViewTables: true,
    canManageTables: true,
    canViewAnalytics: true,
    canManageUsers: true,
  },
}

